events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name j14d106.p.ssafy.io;

        location /.well-known/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name j14d106.p.ssafy.io;

        ssl_certificate /etc/letsencrypt/live/j14d106.p.ssafy.io/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/j14d106.p.ssafy.io/private.key;

        location / {
            proxy_pass http://backend:8050;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 300s;
            proxy_connect_timeout 60s;
            proxy_send_timeout 300s;
        }
    }
}