#!/usr/bin/env bash
set -euo pipefail

# 스크립트 위치를 기준으로 프로젝트 루트로 이동한다.
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

ENV_FILE="${ENV_FILE:-.env}"
CALLER_VENV_DIR="${VENV_DIR-}"
CALLER_HOST="${HOST-}"
CALLER_PORT="${PORT-}"
CALLER_REQUIREMENTS_FILE="${REQUIREMENTS_FILE-}"
CALLER_APP_CACHE_DIR="${APP_CACHE_DIR-}"
CALLER_MODEL_ID="${MODEL_ID-}"
CALLER_LOAD_IN_4BIT="${LOAD_IN_4BIT-}"
CALLER_ANALYZE_MAX_NEW_TOKENS="${ANALYZE_MAX_NEW_TOKENS-}"
CALLER_CHAT_MAX_NEW_TOKENS="${CHAT_MAX_NEW_TOKENS-}"
CALLER_HF_HOME="${HF_HOME-}"
CALLER_TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE-}"
CALLER_XDG_CACHE_HOME="${XDG_CACHE_HOME-}"
CALLER_PIP_CACHE_DIR="${PIP_CACHE_DIR-}"
CALLER_PIP_NO_CACHE_DIR="${PIP_NO_CACHE_DIR-}"
CALLER_TMPDIR="${TMPDIR-}"
CALLER_TMP="${TMP-}"
CALLER_TEMP="${TEMP-}"
CALLER_HF_HUB_DISABLE_XET="${HF_HUB_DISABLE_XET-}"
CALLER_HF_HUB_OFFLINE="${HF_HUB_OFFLINE-}"
CALLER_TRANSFORMERS_OFFLINE="${TRANSFORMERS_OFFLINE-}"
CALLER_USE_SYSTEM_SITE_PACKAGES="${USE_SYSTEM_SITE_PACKAGES-}"

# .env가 있으면 먼저 읽고, 호출 시 넘긴 환경변수는 다시 우선 적용한다.
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
fi

VENV_DIR="${CALLER_VENV_DIR:-${VENV_DIR:-.venv}}"
HOST="${CALLER_HOST:-${HOST:-0.0.0.0}}"
PORT="${CALLER_PORT:-${PORT:-8000}}"
REQUIREMENTS_FILE="${CALLER_REQUIREMENTS_FILE:-${REQUIREMENTS_FILE:-requirements-server.txt}}"
APP_CACHE_DIR="${CALLER_APP_CACHE_DIR:-${APP_CACHE_DIR:-$ROOT_DIR/.cache}}"
MODEL_ID="${CALLER_MODEL_ID:-${MODEL_ID:-Qwen/Qwen2.5-7B-Instruct}}"
LOAD_IN_4BIT="${CALLER_LOAD_IN_4BIT:-${LOAD_IN_4BIT:-1}}"
ANALYZE_MAX_NEW_TOKENS="${CALLER_ANALYZE_MAX_NEW_TOKENS:-${ANALYZE_MAX_NEW_TOKENS:-256}}"
CHAT_MAX_NEW_TOKENS="${CALLER_CHAT_MAX_NEW_TOKENS:-${CHAT_MAX_NEW_TOKENS:-160}}"
HF_HOME="${CALLER_HF_HOME:-${HF_HOME:-$APP_CACHE_DIR/huggingface}}"
TRANSFORMERS_CACHE="${CALLER_TRANSFORMERS_CACHE:-${TRANSFORMERS_CACHE:-$APP_CACHE_DIR/huggingface}}"
XDG_CACHE_HOME="${CALLER_XDG_CACHE_HOME:-${XDG_CACHE_HOME:-$APP_CACHE_DIR}}"
PIP_CACHE_DIR="${CALLER_PIP_CACHE_DIR:-${PIP_CACHE_DIR:-$APP_CACHE_DIR/pip}}"
PIP_NO_CACHE_DIR="${CALLER_PIP_NO_CACHE_DIR:-${PIP_NO_CACHE_DIR:-1}}"
TMPDIR="${CALLER_TMPDIR:-${TMPDIR:-$APP_CACHE_DIR/tmp}}"
TMP="${CALLER_TMP:-${TMP:-$APP_CACHE_DIR/tmp}}"
TEMP="${CALLER_TEMP:-${TEMP:-$APP_CACHE_DIR/tmp}}"
HF_HUB_DISABLE_XET="${CALLER_HF_HUB_DISABLE_XET:-${HF_HUB_DISABLE_XET:-1}}"
HF_HUB_OFFLINE="${CALLER_HF_HUB_OFFLINE:-${HF_HUB_OFFLINE:-0}}"
TRANSFORMERS_OFFLINE="${CALLER_TRANSFORMERS_OFFLINE:-${TRANSFORMERS_OFFLINE:-0}}"
USE_SYSTEM_SITE_PACKAGES="${CALLER_USE_SYSTEM_SITE_PACKAGES:-${USE_SYSTEM_SITE_PACKAGES:-}}"

export HOST PORT MODEL_ID LOAD_IN_4BIT ANALYZE_MAX_NEW_TOKENS CHAT_MAX_NEW_TOKENS
export HF_HOME TRANSFORMERS_CACHE XDG_CACHE_HOME PIP_CACHE_DIR PIP_NO_CACHE_DIR
export TMPDIR TMP TEMP HF_HUB_DISABLE_XET HF_HUB_OFFLINE TRANSFORMERS_OFFLINE

if [ ! -f "$REQUIREMENTS_FILE" ]; then
  REQUIREMENTS_FILE="requirements.txt"
fi

if [ -z "$USE_SYSTEM_SITE_PACKAGES" ] && [ "$REQUIREMENTS_FILE" = "requirements-server.txt" ]; then
  USE_SYSTEM_SITE_PACKAGES=1
fi

mkdir -p "$APP_CACHE_DIR"
mkdir -p "$TMPDIR"

if [ ! -x "$VENV_DIR/bin/python" ]; then
  echo "[INFO] 가상환경이 없어 새로 생성합니다."
  if [ "$USE_SYSTEM_SITE_PACKAGES" = "1" ]; then
    python3 -m venv "$VENV_DIR" --system-site-packages
  else
    python3 -m venv "$VENV_DIR"
  fi
fi

# 가상환경을 활성화하고 필요한 패키지를 설치한다.
source "$VENV_DIR/bin/activate"
python -m pip install --upgrade pip
python -m pip install -r "$REQUIREMENTS_FILE"

echo "[INFO] AI 서버를 시작합니다."
echo "[INFO] HOST=$HOST PORT=$PORT"
echo "[INFO] MODEL_ID=$MODEL_ID"
echo "[INFO] LOAD_IN_4BIT=$LOAD_IN_4BIT"
echo "[INFO] REQUIREMENTS_FILE=$REQUIREMENTS_FILE"
echo "[INFO] HF_HOME=$HF_HOME"
echo "[INFO] TMPDIR=$TMPDIR"

exec python chatbot.py --host "$HOST" --port "$PORT"
